qt_commandline_option(vkb-sensitive-debug TYPE boolean)
qt_commandline_option(vkb-arrow-keynavigation TYPE boolean)
qt_commandline_option(vkb-enable TYPE enableLang)
qt_commandline_option(vkb-disable TYPE disableLang)
qt_commandline_option(vkb-desktop TYPE boolean)
qt_commandline_option(vkb-cangjie TYPE boolean VALUE cangjie)
qt_commandline_option(vkb-zhuyin TYPE boolean VALUE zhuyin)
qt_commandline_option(vkb-hunspell TYPE enum VALUES no 3rdparty system)
qt_commandline_option(vkb-style TYPE string VALUES standard retro none)
qt_commandline_option(vkb-no-bundle-pinyin TYPE boolean)
qt_commandline_option(vkb-no-bundle-tcime TYPE boolean)
